# Generated by Django 5.2.7 on 2025-11-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='limit_by_gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='limit_by_session',
            field=models.CharField(blank=True, choices=[('Weekend', 'Weekend_Students'), ('Weekday', 'Weekday_Students')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='limit_by_sponsorship',
            field=models.CharField(blank=True, choices=[('Government', 'Government'), ('Private', 'Private')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='session_category',
            field=models.CharField(blank=True, choices=[('Weekend', 'Weekend_Students'), ('Weekday', 'Weekday_Students')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='sponsorship_type',
            field=models.CharField(blank=True, choices=[('Government', 'Government'), ('Private', 'Private')], max_length=20, null=True),
        ),
    ]
