# Generated by Django 5.2.8 on 2025-11-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0003_party_candidate_candidate_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='name',
            field=models.CharField(choices=[('NRM', 'National Resistance Movement'), ('NUP', 'National Unity Platform'), ('FDC', 'Forum for Democratic Change'), ('DP', 'Democratic Party'), ('UPC', "Uganda People's Congress"), ('JEEMA', 'Justice Forum'), ('PPP', "People's Progressive Party"), ('ANT', 'Alliance for National Transformation'), ('IND', 'Independent')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='limit_by_session',
            field=models.CharField(blank=True, choices=[('Weekend', 'Weekend'), ('Weekday', 'Weekday')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='session_category',
            field=models.CharField(blank=True, choices=[('Weekend', 'Weekend'), ('Weekday', 'Weekday')], max_length=30, null=True),
        ),
    ]
